[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
ba-server = { workspace = true, optional = true }


[features]
default = []
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "ba-server"]
