[package]
name = "mobile"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
ba-server = { workspace = true, optional = true }


[features]
default = []
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "ba-server"]
