[package]
name = "ba-server"
version = "0.1.0"
authors = ["Bananabit <bananabit@web.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { workspace = true, features = ["server"] }
ui = { workspace = true }


# Web server
tokio = { version = "1.47.1"}
axum = {version = "0.8.4"}
tower-http = {version = "0.6.6",features = ["fs"]}
dioxus-server = { version = "0.7.0-rc.0"}
